version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_boot
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pond
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
